# Generated by Django 4.2.7 on 2023-11-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bb_additionalimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bb',
            old_name='contact',
            new_name='contacts',
        ),
    ]
