# Generated by Django 4.2.7 on 2023-11-23 18:15

from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_contact_bb_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalimage',
            options={'verbose_name': 'Дополнительная иллюстрация', 'verbose_name_plural': 'Дополнительные иллюстрации'},
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Прошёл активацию?'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='Слать оповещения о новых комментариях?'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Выводить в списке?'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='Автор')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Выводить на экран?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликован')),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bb', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
    ]
